name: CI - UI tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ui-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install
        run: npm ci

      - name: Run Cypress (UI) - Smoke Test
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/exercicio2_commitquality_tests/1-tela-login.cy.js
          browser: chrome

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts-ui
          path: |
            cypress/screenshots
            cypress/videos
          if-no-files-found: ignore
